<?php

use Illuminate\Database\Seeder;

class DownloadsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('downloads')->delete();
        
        \DB::table('downloads')->insert(array (
            0 => 
            array (
                'id' => 23,
                'title' => 'Designer Desk Essentials',
                'image' => 'downloads/March2017/download-039.jpg',
                'slug' => 'designer-desk-essentials',
                'description' => '<p>We\'re happy to offer you this awesome PSD mock-up that you can use to create custom hero images for your portfolio page, profile cover and more. All objects, shadows and background are separated so you can build your own composition with ease.</p>
<p>The package also includes 4 ready-made PSD scenes and 2 seamless wooden textures.</p>',
                'file' => 'https://s3-us-west-1.amazonaws.com/getpixelapp/downloads/download-039.zip',
                'tags_relationship' => '',
                'active' => 1,
                'likes' => 0,
                'downloads' => 0,
                'category_id' => 6,
                'time_download' => '2017-03-24 12:00:00',
                'created_at' => '2015-09-13 16:02:00',
                'updated_at' => '2017-03-15 02:25:59',
            ),
            1 => 
            array (
                'id' => 24,
                'title' => 'Free PSD: Ui Kit',
                'image' => 'downloads/March2017/download-001.jpg',
                'slug' => 'free-psd-ui-kit',
            'description' => '<p>Here\'s a UI Kit brought to you by&nbsp;David Minty. This UI Kit features a video player, graphs, forms, maps, and so much more. Feel free to download and use as you wish :)</p>',
            'file' => 'https://s3-us-west-1.amazonaws.com/getpixelapp/downloads/download-001.zip',
            'tags_relationship' => '',
            'active' => 1,
            'likes' => 0,
            'downloads' => 1,
            'category_id' => 7,
            'time_download' => '2015-10-20 13:27:21',
            'created_at' => '2015-09-13 15:22:00',
            'updated_at' => '2017-03-17 06:51:35',
        ),
        2 => 
        array (
            'id' => 25,
            'title' => 'Stream UI PSD',
            'image' => 'downloads/March2017/download-002.jpg',
            'slug' => 'stream-ui-psd',
            'description' => '<p>Stream PSD theme for a video/episode type of website. Please download and use as needed. Looks best if you have the "Gotham" font family installed.</p>',
            'file' => 'https://s3-us-west-1.amazonaws.com/getpixelapp/downloads/download-002.zip',
            'tags_relationship' => '',
            'active' => 1,
            'likes' => 0,
            'downloads' => 0,
            'category_id' => 2,
            'time_download' => '2017-03-24 12:00:00',
            'created_at' => '2015-09-13 16:34:00',
            'updated_at' => '2017-03-15 02:49:04',
        ),
        3 => 
        array (
            'id' => 26,
            'title' => '40 Flat Icon Pack',
            'image' => 'downloads/March2017/download-003.jpg',
            'slug' => '40-flat-icon-pack',
            'description' => '<p>40 free flat Icons.&nbsp;They are part of Squid.ink Flat Icon Pack which are consistent pixel perfect icons ready to use. These&nbsp;icons have been specially built to match the current design trends and to help you expand on your projects.These beautiful icons are perfect to create a unique design experience.</p>',
            'file' => 'https://s3-us-west-1.amazonaws.com/getpixelapp/downloads/download-003.zip',
            'tags_relationship' => '',
            'active' => 1,
            'likes' => 0,
            'downloads' => 0,
            'category_id' => 3,
            'time_download' => '2017-03-24 12:00:00',
            'created_at' => '2015-09-13 16:45:00',
            'updated_at' => '2017-03-15 02:16:02',
        ),
        4 => 
        array (
            'id' => 27,
            'title' => 'Flat & Clean UI Kit',
            'image' => 'downloads/March2017/download-004.jpg',
            'slug' => 'flat-clean-ui-kit',
            'description' => '<p>A free retina ready UI Kit. Contains Calendars, Graphs, and a bunch of other cool looking cards to make an awesome dashboard.</p>',
            'file' => 'https://s3-us-west-1.amazonaws.com/getpixelapp/downloads/download-004.zip',
            'tags_relationship' => '',
            'active' => 1,
            'likes' => 0,
            'downloads' => 0,
            'category_id' => 7,
            'time_download' => '2017-03-24 12:00:00',
            'created_at' => '2015-09-13 16:53:00',
            'updated_at' => '2017-03-15 02:30:43',
        ),
        5 => 
        array (
            'id' => 28,
            'title' => 'Macbook Air Mockup',
            'image' => 'downloads/March2017/download-005.png',
            'slug' => 'macbook-air-mockup',
            'description' => '<p>Free Macbook air PSD mockup. This one is more summertime inspired, the mockup is fully editable and everything is on its own layer, from the effects to some of the details!</p>',
            'file' => 'https://s3-us-west-1.amazonaws.com/getpixelapp/downloads/download-005.zip',
            'tags_relationship' => '',
            'active' => 1,
            'likes' => 0,
            'downloads' => 0,
            'category_id' => 1,
            'time_download' => '2017-03-24 12:00:00',
            'created_at' => '2015-09-13 16:56:00',
            'updated_at' => '2017-03-15 02:39:29',
        ),
        6 => 
        array (
            'id' => 29,
            'title' => 'Freelancer Site PSD',
            'image' => 'downloads/March2017/download-006.png',
            'slug' => 'freelancer-site-psd',
            'description' => '<p>Need to create a freelance site or something similar. Feel free to use this freelancer PSD in your project.</p>
<p>Feel free to download .psd file!</p>
<p>Enjoy!</p>',
            'file' => 'https://s3-us-west-1.amazonaws.com/getpixelapp/downloads/download-006.zip',
            'tags_relationship' => '',
            'active' => 1,
            'likes' => 0,
            'downloads' => 0,
            'category_id' => 2,
            'time_download' => '2017-03-24 12:00:00',
            'created_at' => '2015-09-13 16:59:00',
            'updated_at' => '2017-03-15 02:35:21',
        ),
        7 => 
        array (
            'id' => 30,
            'title' => 'Startup Framework Presentation',
            'image' => 'downloads/March2017/download-007.png',
            'slug' => 'startup-framework-presentation',
            'description' => '<p>This file contains a lot of designs that you can use for your personal site, blog site, or any other site you can think of. Download and use these site designs for free.</p>',
            'file' => 'https://s3-us-west-1.amazonaws.com/getpixelapp/downloads/download-007.zip',
            'tags_relationship' => '',
            'active' => 1,
            'likes' => 0,
            'downloads' => 0,
            'category_id' => 6,
            'time_download' => '2017-03-24 12:00:00',
            'created_at' => '2015-09-14 00:17:00',
            'updated_at' => '2017-03-15 02:48:44',
        ),
        8 => 
        array (
            'id' => 31,
            'title' => 'Free Dashboard PSD',
            'image' => 'downloads/March2017/download-008.png',
            'slug' => 'free-dashboard-psd',
            'description' => '<p>Download this free dashboard. This dashboard design is built to display conversions. You can feel free to use this design for any kind of dashboard you would like.</p>',
            'file' => 'https://s3-us-west-1.amazonaws.com/getpixelapp/downloads/download-008.zip',
            'tags_relationship' => '',
            'active' => 1,
            'likes' => 0,
            'downloads' => 0,
            'category_id' => 2,
            'time_download' => '2017-03-24 12:00:00',
            'created_at' => '2015-09-14 00:24:00',
            'updated_at' => '2017-03-15 02:31:26',
        ),
        9 => 
        array (
            'id' => 32,
            'title' => 'E-commerce Free PSD',
            'image' => 'downloads/March2017/download-009.jpg',
            'slug' => 'e-commerce-free-psd',
            'description' => '<p>This is a clean and simple PSD design. You can download this file for free and use it on any site you would like.</p>',
            'file' => 'https://s3-us-west-1.amazonaws.com/getpixelapp/downloads/download-001.zip',
            'tags_relationship' => '',
            'active' => 1,
            'likes' => 0,
            'downloads' => 0,
            'category_id' => 2,
            'time_download' => '2017-03-24 12:00:00',
            'created_at' => '2015-09-14 00:26:00',
            'updated_at' => '2017-03-15 02:28:31',
        ),
        10 => 
        array (
            'id' => 33,
            'title' => 'Creative Portfolio Template',
            'image' => 'downloads/March2017/download-010.jpg',
            'slug' => 'creative-portfolio-template',
        'description' => '<p>This FREE PSD Resource comes from a&nbsp;Creative Portfolio Bootstrap 3 Template &ndash; REEN! It is pixel perfect (nearly ;), well organized in layers, based on the Bootstrap 3 Grid System and includes hover and on scroll states as well!</p>',
            'file' => 'https://s3-us-west-1.amazonaws.com/getpixelapp/downloads/download-010.zip',
            'tags_relationship' => '',
            'active' => 1,
            'likes' => 0,
            'downloads' => 0,
            'category_id' => 2,
            'time_download' => '2017-03-24 12:00:00',
            'created_at' => '2015-09-14 00:34:00',
            'updated_at' => '2017-03-15 02:25:09',
        ),
        11 => 
        array (
            'id' => 34,
            'title' => 'Free Google Watch PSD',
            'image' => 'downloads/March2017/download-011.jpg',
            'slug' => 'free-google-watch-psd',
        'description' => '<p>Checkout this awesome Google watch. Download the free PSD and use as you wish :)</p>',
        'file' => 'https://s3-us-west-1.amazonaws.com/getpixelapp/downloads/download-011.zip',
        'tags_relationship' => '',
        'active' => 1,
        'likes' => 0,
        'downloads' => 0,
        'category_id' => 2,
        'time_download' => '2017-03-24 12:00:00',
        'created_at' => '2015-09-14 00:36:00',
        'updated_at' => '2017-03-15 02:32:20',
    ),
    12 => 
    array (
        'id' => 35,
        'title' => 'Movie Store PSD',
        'image' => 'downloads/March2017/download-012.jpg',
        'slug' => 'movie-store-psd',
        'description' => '<p>Checkout this awesome movie store PSD. All the movies from Marvel studio and here is UI / UX of MovieStore for free PSD!</p>',
        'file' => 'https://s3-us-west-1.amazonaws.com/getpixelapp/downloads/download-012.zip',
        'tags_relationship' => '',
        'active' => 1,
        'likes' => 0,
        'downloads' => 4,
        'category_id' => 8,
        'time_download' => '2017-03-24 12:00:00',
        'created_at' => '2015-09-14 00:37:00',
        'updated_at' => '2017-03-15 02:40:25',
    ),
    13 => 
    array (
        'id' => 36,
        'title' => 'Simple Admin Dashboard UI',
        'image' => 'downloads/March2017/download-013.jpg',
        'slug' => 'simple-admin-dashboard-ui',
        'description' => '<p>Checkout this awesome simple Dashboard UI. The fonts used are Melbourne and Montserat.</p>',
        'file' => 'https://s3-us-west-1.amazonaws.com/getpixelapp/downloads/download-013.zip',
        'tags_relationship' => '',
        'active' => 1,
        'likes' => 0,
        'downloads' => 0,
        'category_id' => 2,
        'time_download' => '2017-03-24 12:00:00',
        'created_at' => '2015-09-20 16:58:00',
        'updated_at' => '2017-03-15 02:47:58',
    ),
    14 => 
    array (
        'id' => 37,
        'title' => 'Gaming Landing Page',
        'image' => 'downloads/March2017/download-014.jpg',
        'slug' => 'gaming-landing-page',
        'description' => '<p>A really nice template that you can you use for gaming websites. This freebie was created by Aleksandar Nikcevic.</p>',
        'file' => 'https://s3-us-west-1.amazonaws.com/getpixelapp/downloads/download-014.zip',
        'tags_relationship' => '',
        'active' => 1,
        'likes' => 0,
        'downloads' => 1,
        'category_id' => 8,
        'time_download' => '2015-10-13 19:33:35',
        'created_at' => '2015-09-20 16:59:00',
        'updated_at' => '2017-03-15 02:36:05',
    ),
    15 => 
    array (
        'id' => 38,
        'title' => 'Dingole Web App',
        'image' => 'downloads/March2017/download-015.jpg',
        'slug' => 'dingole-web-app',
        'description' => '<p>Awesome free website PSD design that you can use for any web project. Please feel free to download and use as you wish.</p>',
        'file' => 'https://s3-us-west-1.amazonaws.com/getpixelapp/downloads/download-015.zip',
        'tags_relationship' => '',
        'active' => 1,
        'likes' => 0,
        'downloads' => 0,
        'category_id' => 2,
        'time_download' => '2017-03-24 12:00:00',
        'created_at' => '2015-09-20 17:00:00',
        'updated_at' => '2017-03-15 02:27:33',
    ),
    16 => 
    array (
        'id' => 39,
        'title' => 'Clean Macbook Air Mockup',
        'image' => 'downloads/March2017/download-016.jpg',
        'slug' => 'clean-macbook-air-mockup',
        'description' => '<p>Checkout this clean macbook air mockup. Simply open up the file, edit the smart object, save the smart object and you are good to go. Feel free to use as you wish.</p>',
        'file' => 'https://s3-us-west-1.amazonaws.com/getpixelapp/downloads/download-016.zip',
        'tags_relationship' => '',
        'active' => 1,
        'likes' => 0,
        'downloads' => 1,
        'category_id' => 1,
        'time_download' => '2015-10-13 19:31:28',
        'created_at' => '2015-09-22 01:05:00',
        'updated_at' => '2017-03-15 02:18:16',
    ),
    17 => 
    array (
        'id' => 40,
        'title' => '2 Macbook Pro Mockups',
        'image' => 'downloads/March2017/download-017.jpg',
        'slug' => '2-macbook-pro-mockups',
        'description' => '<p>Download these free macbook mockups. Here are 2 clean and ready to use macbook mockups to use for your design.</p>',
        'file' => 'https://s3-us-west-1.amazonaws.com/getpixelapp/downloads/download-017.zip',
        'tags_relationship' => '',
        'active' => 1,
        'likes' => 0,
        'downloads' => 2,
        'category_id' => 1,
        'time_download' => '2015-10-13 19:29:10',
        'created_at' => '2015-09-22 01:06:00',
        'updated_at' => '2017-03-15 02:15:49',
    ),
    18 => 
    array (
        'id' => 41,
        'title' => 'Fire UI Kit',
        'image' => 'downloads/March2017/download-018.jpg',
        'slug' => 'fire-ui-kit',
        'description' => '<p>Download this free UI Kit. Use any of these elements in your design. This UI kit will go nicely with any website.</p>',
        'file' => 'https://s3-us-west-1.amazonaws.com/getpixelapp/downloads/download-018.zip',
        'tags_relationship' => '',
        'active' => 1,
        'likes' => 1,
        'downloads' => 3,
        'category_id' => 7,
        'time_download' => '2017-03-18 12:01:38',
        'created_at' => '2015-09-22 01:07:00',
        'updated_at' => '2017-03-18 12:01:38',
    ),
    19 => 
    array (
        'id' => 42,
        'title' => 'Clean UI Kit',
        'image' => 'downloads/March2017/download-020.jpg',
        'slug' => 'clean-ui-kit',
        'description' => '<p>This is an awesome free, flat UI Kit that you can use for any of your projects.</p>',
        'file' => 'https://s3-us-west-1.amazonaws.com/getpixelapp/downloads/download-020.zip',
        'tags_relationship' => '',
        'active' => 1,
        'likes' => 0,
        'downloads' => 0,
        'category_id' => 7,
        'time_download' => '2017-03-24 12:00:00',
        'created_at' => '2015-10-14 01:27:00',
        'updated_at' => '2017-03-15 02:22:56',
    ),
    20 => 
    array (
        'id' => 43,
        'title' => 'Free Masonry PSD',
        'image' => 'downloads/March2017/download-019.jpg',
        'slug' => 'free-masonry-psd',
        'description' => '<p>You can use this masony PSD design to build your own website. Use this design for any project you would like.</p>',
        'file' => 'https://s3-us-west-1.amazonaws.com/getpixelapp/downloads/download-019.zip',
        'tags_relationship' => '',
        'active' => 1,
        'likes' => 0,
        'downloads' => 0,
        'category_id' => 8,
        'time_download' => '2017-03-24 12:00:00',
        'created_at' => '2015-10-14 01:29:00',
        'updated_at' => '2017-03-15 02:32:51',
    ),
    21 => 
    array (
        'id' => 44,
        'title' => 'Olivia Landing Page Template',
        'image' => 'downloads/March2017/download-021.jpg',
        'slug' => 'olivia-landing-page-template',
        'description' => '<p>Olivia is a vibrant landing page template that can be used for both your personal and client webpage. Many thanks to Shahin Srowar for this freebie.</p>',
        'file' => 'https://s3-us-west-1.amazonaws.com/getpixelapp/downloads/download-021.zip',
        'tags_relationship' => '',
        'active' => 1,
        'likes' => 0,
        'downloads' => 0,
        'category_id' => 8,
        'time_download' => '2017-03-24 12:00:00',
        'created_at' => '2015-10-14 14:30:00',
        'updated_at' => '2017-03-15 02:40:53',
    ),
    22 => 
    array (
        'id' => 45,
        'title' => 'Roady – Traveler Dashboard',
        'image' => 'downloads/March2017/download-022.jpg',
        'slug' => 'roady-traveler-dashboard',
        'description' => '<p>Roady is a vibrant dashboard made for travel statistics. The author of this resource is Max Dmytriv.</p>',
        'file' => 'https://s3-us-west-1.amazonaws.com/getpixelapp/downloads/download-022.zip',
        'tags_relationship' => '',
        'active' => 1,
        'likes' => 0,
        'downloads' => 0,
        'category_id' => 8,
        'time_download' => '2017-03-24 12:00:00',
        'created_at' => '2015-10-14 14:32:00',
        'updated_at' => '2017-03-15 02:42:30',
    ),
    23 => 
    array (
        'id' => 46,
        'title' => 'Arkenea Template',
        'image' => 'downloads/March2017/download-023.jpg',
        'slug' => 'arkenea-template',
        'description' => '<p>Arkenea is a template great for creating a website for a creative agency or for even a personal one. This freebie was created by Prashant Dwivedi.</p>',
        'file' => 'https://s3-us-west-1.amazonaws.com/getpixelapp/downloads/download-023.zip',
        'tags_relationship' => '',
        'active' => 1,
        'likes' => 0,
        'downloads' => 1,
        'category_id' => 8,
        'time_download' => '2015-10-20 13:28:21',
        'created_at' => '2015-10-14 14:33:00',
        'updated_at' => '2017-03-15 02:16:40',
    ),
    24 => 
    array (
        'id' => 47,
        'title' => 'Realistic iMac Mockup',
        'image' => 'downloads/March2017/download-024.jpg',
        'slug' => 'realistic-imac-mockup',
        'description' => '<p>This is a realistic iMac mockup in a warm environment. This resource was released by Kaushal Panchal.</p>',
        'file' => 'https://s3-us-west-1.amazonaws.com/getpixelapp/downloads/download-024.zip',
        'tags_relationship' => '',
        'active' => 1,
        'likes' => 0,
        'downloads' => 1,
        'category_id' => 1,
        'time_download' => '2017-03-23 16:26:44',
        'created_at' => '2015-10-21 04:00:00',
        'updated_at' => '2017-03-23 16:26:44',
    ),
    25 => 
    array (
        'id' => 48,
        'title' => 'Web Browser Mockup',
        'image' => 'downloads/March2017/download-025.jpg',
        'slug' => 'web-browser-mockup',
        'description' => '<p>Here is a great Safari browser mockup that you can use to display your apps or designs. Big thanks to Mats-Peter Forss for this freebie.</p>',
        'file' => 'https://s3-us-west-1.amazonaws.com/getpixelapp/downloads/download-025.zip',
        'tags_relationship' => '',
        'active' => 1,
        'likes' => 0,
        'downloads' => 0,
        'category_id' => 1,
        'time_download' => '2017-03-24 12:00:00',
        'created_at' => '2015-10-21 04:02:00',
        'updated_at' => '2017-03-15 02:50:45',
    ),
    26 => 
    array (
        'id' => 49,
        'title' => 'MacBook Workspace Mockup',
        'image' => 'downloads/March2017/download-026.jpg',
        'slug' => 'macbook-workspace-mockup',
        'description' => '<p>A high resolution Macbook mock-up that helps you showcase your apps and web design projects in a photorealistic environment. In order to display your design on the screen of the Macbook, just place it inside the smart object.</p>',
        'file' => 'https://s3-us-west-1.amazonaws.com/getpixelapp/downloads/download-026.zip',
        'tags_relationship' => '',
        'active' => 1,
        'likes' => 0,
        'downloads' => 0,
        'category_id' => 1,
        'time_download' => '2017-03-24 12:00:00',
        'created_at' => '2015-10-21 04:04:00',
        'updated_at' => '2017-03-15 02:40:00',
    ),
    27 => 
    array (
        'id' => 50,
        'title' => 'UI Kit Based On Bootstrap',
        'image' => 'downloads/March2017/download-027.jpg',
        'slug' => 'ui-kit-based-on-bootstrap',
        'description' => '<p>This UI Kit based on bootstrap 3 can be implemented into any web app or web project. Feel free to download it and use as you wish</p>',
        'file' => 'https://s3-us-west-1.amazonaws.com/getpixelapp/downloads/download-027.zip',
        'tags_relationship' => '',
        'active' => 1,
        'likes' => 1,
        'downloads' => 3,
        'category_id' => 7,
        'time_download' => '2017-03-24 12:38:59',
        'created_at' => '2015-10-22 13:48:00',
        'updated_at' => '2017-03-24 12:38:59',
    ),
    28 => 
    array (
        'id' => 51,
        'title' => 'Craftyicons',
        'image' => 'downloads/March2017/download-028.jpg',
        'slug' => 'craftyicons',
        'description' => '<p>Craftyicons is a free set of line icons that you can use in any web app or web project</p>',
        'file' => 'https://s3-us-west-1.amazonaws.com/getpixelapp/downloads/download-028.zip',
        'tags_relationship' => '',
        'active' => 1,
        'likes' => 0,
        'downloads' => 0,
        'category_id' => 3,
        'time_download' => '2017-03-24 12:00:00',
        'created_at' => '2015-10-22 13:49:00',
        'updated_at' => '2017-03-15 02:23:44',
    ),
    29 => 
    array (
        'id' => 52,
        'title' => 'Kvasir 180+ Icons',
        'image' => 'downloads/March2017/download-029.png',
        'slug' => 'kvasir-180-icons',
        'description' => '<p>Set of free flat icons. These awesome flat icons will add a nice touch to any project.</p>',
        'file' => 'https://s3-us-west-1.amazonaws.com/getpixelapp/downloads/download-029.zip',
        'tags_relationship' => '',
        'active' => 1,
        'likes' => 0,
        'downloads' => 1,
        'category_id' => 3,
        'time_download' => '2015-10-23 01:45:12',
        'created_at' => '2015-10-22 13:51:00',
        'updated_at' => '2017-03-15 02:38:34',
    ),
    30 => 
    array (
        'id' => 53,
        'title' => 'Just Another UI Kit',
        'image' => 'downloads/March2017/download-030.jpg',
        'slug' => 'just-another-ui-kit',
        'description' => '<p>Another clean UI Kit. This is a clean flat UI Kit PSD Download. This UI Kit has buttons, graphs, calendars, and much more.</p>',
        'file' => 'https://s3-us-west-1.amazonaws.com/getpixelapp/downloads/download-030.zip',
        'tags_relationship' => '',
        'active' => 1,
        'likes' => 0,
        'downloads' => 1,
        'category_id' => 7,
        'time_download' => '2017-03-18 12:28:22',
        'created_at' => '2015-10-22 14:18:00',
        'updated_at' => '2017-03-18 12:28:22',
    ),
    31 => 
    array (
        'id' => 54,
        'title' => '170 Line Icons',
        'image' => 'downloads/March2017/download-031.png',
        'slug' => '170-line-icons',
        'description' => '<p>Gorgeous set of 170 diverse line icons. This resource was handcrafted by Creative Boxx.</p>',
        'file' => 'https://s3-us-west-1.amazonaws.com/getpixelapp/downloads/download-031.zip',
        'tags_relationship' => '',
        'active' => 1,
        'likes' => 0,
        'downloads' => 0,
        'category_id' => 3,
        'time_download' => '2017-03-24 12:00:00',
        'created_at' => '2015-10-22 14:18:00',
        'updated_at' => '2017-03-15 02:14:44',
    ),
    32 => 
    array (
        'id' => 55,
        'title' => 'Uzers UI Kit',
        'image' => 'downloads/March2017/download-032.jpg',
        'slug' => 'uzers-ui-kit',
        'description' => '<p>This free UI Kit comes with many beatiful designs and elements for you to use in your next web project.</p>',
        'file' => 'https://s3-us-west-1.amazonaws.com/getpixelapp/downloads/download-032.zip',
        'tags_relationship' => '',
        'active' => 1,
        'likes' => 0,
        'downloads' => 1,
        'category_id' => 7,
        'time_download' => '2017-03-18 21:00:29',
        'created_at' => '2015-10-22 14:20:00',
        'updated_at' => '2017-03-18 21:00:29',
    ),
    33 => 
    array (
        'id' => 56,
        'title' => 'Birply icons set',
        'image' => 'downloads/March2017/download-033.jpg',
        'slug' => 'birply-icons-set',
        'description' => '<p>Birply is a set of 28 minimal but elegant icons created with Adobe Illustrator. Free Ai and SVG designed and released by Davide Pacilio.</p>',
        'file' => 'https://s3-us-west-1.amazonaws.com/getpixelapp/downloads/download-033.zip',
        'tags_relationship' => '',
        'active' => 1,
        'likes' => 0,
        'downloads' => 1,
        'category_id' => 9,
        'time_download' => '2017-03-24 12:40:43',
        'created_at' => '2015-10-22 15:29:00',
        'updated_at' => '2017-03-24 12:40:43',
    ),
    34 => 
    array (
        'id' => 57,
        'title' => 'Geometric weather icons',
        'image' => 'downloads/March2017/download-034.jpg',
        'slug' => 'geometric-weather-icons',
    'description' => '<p>A small set including 8 animated geometric weather icons created with Illustrator. Free AI and AEP (After Effects animation) by Hanna Jung.</p>',
        'file' => 'https://s3-us-west-1.amazonaws.com/getpixelapp/downloads/download-034.zip',
        'tags_relationship' => '',
        'active' => 1,
        'likes' => 1,
        'downloads' => 2,
        'category_id' => 9,
        'time_download' => '2017-03-18 16:22:44',
        'created_at' => '2015-10-22 15:30:00',
        'updated_at' => '2017-03-18 16:22:44',
    ),
    35 => 
    array (
        'id' => 58,
        'title' => '6 vintage logo kit',
        'image' => 'downloads/March2017/download-035.jpg',
        'slug' => '6-vintage-logo-kit',
    'description' => '<p>A vintage starter kit including 6 Logo / Insignias (AI), 12 Icons (AI), an ABR brush file for Photoshop to add texture to your final piece using the Eraser Tool.</p>',
        'file' => 'https://s3-us-west-1.amazonaws.com/getpixelapp/downloads/download-035.zip',
        'tags_relationship' => '',
        'active' => 1,
        'likes' => 1,
        'downloads' => 1,
        'category_id' => 9,
        'time_download' => '2017-03-17 15:33:30',
        'created_at' => '2015-10-22 15:31:00',
        'updated_at' => '2017-03-18 13:17:20',
    ),
    36 => 
    array (
        'id' => 59,
        'title' => 'Land.io – Landing page UI kit',
        'image' => 'downloads/March2017/download-036.jpg',
        'slug' => 'landio-landing-page-ui-kit',
        'description' => '<p>Land.io is a beautiful UI kit designed in Sketch for creating landing pages. It includes many useful elements ready to be reused in your projects. Freebie created and released by Peter Finlan.</p>',
        'file' => 'https://s3-us-west-1.amazonaws.com/getpixelapp/downloads/download-036.zip',
        'tags_relationship' => '',
        'active' => 1,
        'likes' => 0,
        'downloads' => 1,
        'category_id' => 5,
        'time_download' => '2017-03-20 14:14:02',
        'created_at' => '2015-10-22 15:36:00',
        'updated_at' => '2017-03-20 14:14:02',
    ),
    37 => 
    array (
        'id' => 60,
        'title' => 'Sedna – One page website template',
        'image' => 'downloads/March2017/download-037.jpg',
        'slug' => 'sedna-one-page-website-template',
    'description' => '<p>Sedna is a responsive one page website template designed with Sketch and coded with the latest web technologies (HTML5/CSS3). Freebie released by Peter Finlan.</p>',
        'file' => 'https://s3-us-west-1.amazonaws.com/getpixelapp/downloads/download-037.zip',
        'tags_relationship' => '',
        'active' => 1,
        'likes' => 2,
        'downloads' => 5,
        'category_id' => 5,
        'time_download' => '2017-03-20 14:06:29',
        'created_at' => '2015-10-22 15:37:00',
        'updated_at' => '2017-03-20 14:06:29',
    ),
    38 => 
    array (
        'id' => 61,
        'title' => 'Free UI kit for Sketch',
        'image' => 'downloads/March2017/download-038.jpg',
        'slug' => 'free-ui-kit-for-sketch',
        'description' => '<p>A free UI kit for Sketch including some generic, widget looking, components you can use for your next project. A freebie released by Apostol Voicu.</p>',
        'file' => 'https://s3-us-west-1.amazonaws.com/getpixelapp/downloads/download-038.zip',
        'tags_relationship' => '',
        'active' => 1,
        'likes' => 1,
        'downloads' => 1,
        'category_id' => 5,
        'time_download' => '2017-03-20 14:10:49',
        'created_at' => '2015-10-22 15:38:00',
        'updated_at' => '2017-03-24 17:23:41',
    ),
    39 => 
    array (
        'id' => 62,
        'title' => 'Instant Message Chat Dashboard',
        'image' => 'downloads/March2017/NQGD0YaC0Itk8Af7zdqr.png',
        'slug' => 'instant-message-chat-dashboard',
        'description' => '<p>Checkout this awesome freebie PSD of an instant message chat dashboard.</p>',
        'file' => 'https://s3-us-west-1.amazonaws.com/getpixelapp/downloads/download-040.zip',
        'tags_relationship' => NULL,
        'active' => 1,
        'likes' => 0,
        'downloads' => 1,
        'category_id' => 1,
        'time_download' => '2017-03-24 17:44:40',
        'created_at' => '2017-03-24 17:44:13',
        'updated_at' => '2017-03-24 17:44:40',
    ),
    40 => 
    array (
        'id' => 63,
        'title' => 'Pex Free PSD Template',
        'image' => 'downloads/March2017/Mwkfi3RuACN6zAqD8NdW.jpg',
        'slug' => 'pex-free-psd-template',
        'description' => '<p>This awesome website design is called Plex. You can download this design for free and use it in any web application or web project.</p>',
        'file' => 'https://s3-us-west-1.amazonaws.com/getpixelapp/downloads/download-041.zip',
        'tags_relationship' => NULL,
        'active' => 1,
        'likes' => 0,
        'downloads' => 0,
        'category_id' => 2,
        'time_download' => '2017-03-24 11:17:37',
        'created_at' => '2017-03-24 18:17:37',
        'updated_at' => '2017-03-24 18:17:37',
    ),
));
        
        
    }
}