<?php

use Illuminate\Database\Seeder;

class MenuItemsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('menu_items')->delete();
        
        \DB::table('menu_items')->insert(array (
            0 => 
            array (
                'id' => 1,
                'menu_id' => 1,
                'title' => 'Dashboard',
                'url' => '/admin',
                'target' => '_self',
                'icon_class' => 'voyager-boat',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 1,
                'created_at' => '2017-02-10 14:18:17',
                'updated_at' => '2017-02-10 14:18:17',
                'route' => NULL,
                'parameters' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'menu_id' => 1,
                'title' => 'Media',
                'url' => '/admin/media',
                'target' => '_self',
                'icon_class' => 'voyager-images',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 7,
                'created_at' => '2017-02-10 14:18:17',
                'updated_at' => '2017-02-10 15:00:40',
                'route' => NULL,
                'parameters' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'menu_id' => 1,
                'title' => 'Posts',
                'url' => '/admin/posts',
                'target' => '_self',
                'icon_class' => 'voyager-news',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 5,
                'created_at' => '2017-02-10 14:18:17',
                'updated_at' => '2017-03-15 01:53:14',
                'route' => NULL,
                'parameters' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'menu_id' => 1,
                'title' => 'Users',
                'url' => '/admin/users',
                'target' => '_self',
                'icon_class' => 'voyager-person',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 8,
                'created_at' => '2017-02-10 14:18:17',
                'updated_at' => '2017-02-10 15:00:40',
                'route' => NULL,
                'parameters' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'menu_id' => 1,
                'title' => 'Categories',
                'url' => '/admin/categories',
                'target' => '_self',
                'icon_class' => 'voyager-categories',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 3,
                'created_at' => '2017-02-10 14:18:17',
                'updated_at' => '2017-03-15 01:53:14',
                'route' => NULL,
                'parameters' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'menu_id' => 1,
                'title' => 'Pages',
                'url' => '/admin/pages',
                'target' => '_self',
                'icon_class' => 'voyager-file-text',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 6,
                'created_at' => '2017-02-10 14:18:17',
                'updated_at' => '2017-03-15 01:53:14',
                'route' => NULL,
                'parameters' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'menu_id' => 1,
                'title' => 'Roles',
                'url' => '/admin/roles',
                'target' => '_self',
                'icon_class' => 'voyager-lock',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 9,
                'created_at' => '2017-02-10 14:18:17',
                'updated_at' => '2017-02-10 15:00:40',
                'route' => NULL,
                'parameters' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'menu_id' => 1,
                'title' => 'Tools',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-tools',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 10,
                'created_at' => '2017-02-10 14:18:17',
                'updated_at' => '2017-02-10 15:00:40',
                'route' => NULL,
                'parameters' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'menu_id' => 1,
                'title' => 'Menu Builder',
                'url' => '/admin/menus',
                'target' => '_self',
                'icon_class' => 'voyager-list',
                'color' => NULL,
                'parent_id' => 8,
                'order' => 1,
                'created_at' => '2017-02-10 14:18:17',
                'updated_at' => '2017-02-10 14:52:56',
                'route' => NULL,
                'parameters' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'menu_id' => 1,
                'title' => 'Database',
                'url' => '/admin/database',
                'target' => '_self',
                'icon_class' => 'voyager-data',
                'color' => NULL,
                'parent_id' => 8,
                'order' => 2,
                'created_at' => '2017-02-10 14:18:17',
                'updated_at' => '2017-02-10 14:52:56',
                'route' => NULL,
                'parameters' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'menu_id' => 1,
                'title' => 'Settings',
                'url' => '/admin/settings',
                'target' => '_self',
                'icon_class' => 'voyager-settings',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 11,
                'created_at' => '2017-02-10 14:18:17',
                'updated_at' => '2017-02-10 15:00:40',
                'route' => NULL,
                'parameters' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'menu_id' => 1,
                'title' => 'Tags',
                'url' => '/admin/tags',
                'target' => '_self',
                'icon_class' => 'voyager-tag',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 4,
                'created_at' => '2017-02-10 14:52:48',
                'updated_at' => '2017-03-15 01:53:14',
                'route' => NULL,
                'parameters' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'menu_id' => 1,
                'title' => 'Downloads',
                'url' => '/admin/downloads',
                'target' => '_self',
                'icon_class' => 'voyager-cloud-download',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 2,
                'created_at' => '2017-02-10 15:00:35',
                'updated_at' => '2017-02-10 15:00:40',
                'route' => NULL,
                'parameters' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'menu_id' => 2,
                'title' => 'Home',
                'url' => '/',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 1,
                'created_at' => '2017-03-16 16:20:06',
                'updated_at' => '2017-03-16 16:21:39',
                'route' => NULL,
                'parameters' => '',
            ),
            14 => 
            array (
                'id' => 15,
                'menu_id' => 2,
                'title' => 'Mockups',
                'url' => '/category/mockups',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 2,
                'created_at' => '2017-03-16 16:20:22',
                'updated_at' => '2017-03-16 16:21:39',
                'route' => NULL,
                'parameters' => '',
            ),
            15 => 
            array (
                'id' => 16,
                'menu_id' => 2,
                'title' => 'PSDs',
                'url' => '/category/psds',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 3,
                'created_at' => '2017-03-16 16:21:00',
                'updated_at' => '2017-03-16 16:21:39',
                'route' => NULL,
                'parameters' => '',
            ),
            16 => 
            array (
                'id' => 17,
                'menu_id' => 2,
                'title' => 'UI Kits',
                'url' => '/category/ui-kits',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 16,
                'order' => 1,
                'created_at' => '2017-03-16 16:21:21',
                'updated_at' => '2017-03-16 16:21:39',
                'route' => NULL,
                'parameters' => '',
            ),
            17 => 
            array (
                'id' => 18,
                'menu_id' => 2,
                'title' => 'Websites',
                'url' => '/category/websites',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 16,
                'order' => 2,
                'created_at' => '2017-03-16 16:21:34',
                'updated_at' => '2017-03-16 16:21:42',
                'route' => NULL,
                'parameters' => '',
            ),
            18 => 
            array (
                'id' => 19,
                'menu_id' => 2,
                'title' => 'Icons',
                'url' => '/category/icons',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 4,
                'created_at' => '2017-03-16 16:22:04',
                'updated_at' => '2017-03-16 16:24:06',
                'route' => NULL,
                'parameters' => '',
            ),
            19 => 
            array (
                'id' => 20,
                'menu_id' => 2,
                'title' => 'Vectors',
                'url' => '/category/vectors',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 5,
                'created_at' => '2017-03-16 16:22:43',
                'updated_at' => '2017-03-16 16:24:06',
                'route' => NULL,
                'parameters' => '',
            ),
            20 => 
            array (
                'id' => 21,
                'menu_id' => 2,
                'title' => 'Illustrator',
                'url' => '/category/illustrator',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 20,
                'order' => 1,
                'created_at' => '2017-03-16 16:23:36',
                'updated_at' => '2017-03-16 16:24:06',
                'route' => NULL,
                'parameters' => '',
            ),
            21 => 
            array (
                'id' => 22,
                'menu_id' => 2,
                'title' => 'Sketch',
                'url' => '/category/sketch',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 20,
                'order' => 2,
                'created_at' => '2017-03-16 16:23:47',
                'updated_at' => '2017-03-16 16:24:09',
                'route' => NULL,
                'parameters' => '',
            ),
            22 => 
            array (
                'id' => 23,
                'menu_id' => 2,
                'title' => 'Other',
                'url' => '/category/other',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 6,
                'created_at' => '2017-03-16 16:23:59',
                'updated_at' => '2017-03-16 16:24:07',
                'route' => NULL,
                'parameters' => '',
            ),
            23 => 
            array (
                'id' => 24,
                'menu_id' => 3,
                'title' => 'Latest',
                'url' => '/latest',
                'target' => '_self',
                'icon_class' => 'fa fa-calendar',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 1,
                'created_at' => '2017-03-22 23:35:18',
                'updated_at' => '2017-03-23 16:05:42',
                'route' => NULL,
                'parameters' => '',
            ),
            24 => 
            array (
                'id' => 25,
                'menu_id' => 3,
                'title' => 'Popular',
                'url' => '/popular',
                'target' => '_self',
                'icon_class' => 'fa fa-star',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 2,
                'created_at' => '2017-03-22 23:35:35',
                'updated_at' => '2017-03-23 16:05:42',
                'route' => NULL,
                'parameters' => '',
            ),
            25 => 
            array (
                'id' => 26,
                'menu_id' => 3,
                'title' => 'About',
                'url' => '/page/about',
                'target' => '_self',
                'icon_class' => 'fa fa-question-circle',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 4,
                'created_at' => '2017-03-22 23:37:16',
                'updated_at' => '2017-03-23 16:05:42',
                'route' => NULL,
                'parameters' => '',
            ),
            26 => 
            array (
                'id' => 27,
                'menu_id' => 3,
                'title' => 'Contact',
                'url' => '/page/contact',
                'target' => '_self',
                'icon_class' => 'fa fa-envelope',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 5,
                'created_at' => '2017-03-22 23:37:57',
                'updated_at' => '2017-03-23 16:05:42',
                'route' => NULL,
                'parameters' => '',
            ),
            27 => 
            array (
                'id' => 28,
                'menu_id' => 4,
                'title' => 'Admin',
                'url' => '/admin',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 16,
                'created_at' => '2017-03-22 23:57:57',
                'updated_at' => '2017-03-22 23:57:57',
                'route' => NULL,
                'parameters' => '',
            ),
            28 => 
            array (
                'id' => 29,
                'menu_id' => 4,
                'title' => 'About',
                'url' => '/page/about',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 17,
                'created_at' => '2017-03-22 23:58:05',
                'updated_at' => '2017-03-22 23:58:05',
                'route' => NULL,
                'parameters' => '',
            ),
            29 => 
            array (
                'id' => 30,
                'menu_id' => 4,
                'title' => 'Contact',
                'url' => '/page/contact',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 18,
                'created_at' => '2017-03-22 23:58:15',
                'updated_at' => '2017-03-22 23:58:15',
                'route' => NULL,
                'parameters' => '',
            ),
            30 => 
            array (
                'id' => 31,
                'menu_id' => 3,
                'title' => 'Blog',
                'url' => '/blog',
                'target' => '_self',
                'icon_class' => 'fa fa-newspaper-o',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 3,
                'created_at' => '2017-03-23 16:05:37',
                'updated_at' => '2017-03-23 16:05:42',
                'route' => NULL,
                'parameters' => '',
            ),
        ));
        
        
    }
}